### ISSUE TITLE
Question: Does the app with this SDK included violate Google Play distribution policy?

### ISSUE THREAD

**Issue by alexeyvasilyev** [martoreto/aauto-sdk#3]
SDK uses unofficially released APIs which are available for some car manufacturers. It is called 'Custom apps' in https://designguidelines.withgoogle.com/android-auto/custom-apps/custom-app-anatomy.html

However it is not clear if using this SDK violates Google Play distribution policy for Android Auto.

**Comment by nerone-github** [comment]
I personally would not publish an app with this SDK on Playstore, until an official sdk is available. As you said its not clear, and probably not wanted. Else they would have made an official SDK. Better not anger Google in the first place ;-) It would be sad if they find a way to block custom apps.

**Comment by martoreto** [comment]
I agree with @nerone-github.

**Comment by martoreto** [comment]
See also:

https://forum.xda-developers.com/general/paid-software/app-obd2-plugin-android-auto-torque-t3657805
"App now available on XDA Labs, sadly Google have rejected it from Play Store, because it does not fall into the Media/Messaging app category."

This is also an app which uses an unofficial Android Auto SDK, albeit a different one.
